const ItemList = [
  {
    id: "#EatPizza01",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza02",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza03",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza04",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza05",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza06",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza07",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza08",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza09",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza10",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza11",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza12",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza13",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza14",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza15",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza16",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza17",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza18",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza19",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza20",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza21",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza22",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza23",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza24",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
  {
    id: "#EatPizza25",
    name: "Maxican Spicy Pizza",
    category: "Pizza",
    isActive: true,
  },
];

export default ItemList;
